In [1]:
import numpy as np
# import mercury as mr
# import pandas as pd


done with forward pass but for each layer but 
- make forward pass in one go
- first create backward pass for regression task (mse loss)

In [21]:
class Dense:
    layers = []
    def __call__(self):
        return self.activation_output
    
    
    def __init__(self, units:int, activation:str, previous_layer):
        self.units = units
        self.activation = activation
        self.previous_layer = np.array(previous_layer)
        
        previous_layer_units = self.previous_layer.shape[0]
        Dense.layers.append(self)
                
                
        # initializing weights and biases of this layer
        self.__weights, self.__biases = self.__initialize_weights_and_biases(previous_layer_units)
        
        # calculating output-> WiXi + Bo
        self.output = np.add(np.dot(self.__weights, self.previous_layer), self.__biases)
        
        if self.activation.lower() == 'relu':
            activation_func = np.vectorize(self.__relu_activation)
            self.activation_output = activation_func(self.output).astype(np.float32)
            
        elif self.activation.lower() == 'sigmoid':
            activation_func = np.vectorize(self.__sigmoid_activation)
            self.activation_output = activation_func(self.output).astype(np.float32)
            
        else: # linear
            self.activation_output = self.output
            
        
        # print("current_layer_units = ",self.units)
        # print("biases_shape = ",self.__biases.shape)
        # print("weights_shape = ",self.__weights.shape)
        # print("previous layer units = ",previous_layer_units)
        # print("previous layer values = ",self.previous_layer)
        # print("Output for next layer is =\n", self.activation_output)
        # print("Dtype Output for next layer is =\n", self.activation_output.dtype)
        
    def loss_calc():
        pass
        
    def __initialize_weights_and_biases(self,previous_layer_units:int):
#         using `he normal` initialization
        biases = np.random.randn(self.units)*np.sqrt(2/previous_layer_units)
        weights = np.random.randn(self.units, previous_layer_units)*np.sqrt(2/previous_layer_units)
        return weights, biases
        
        
    def __relu_activation(self, layer_output:np.array):
        return max(0, layer_output)
    
    
    def __sigmoid_activation(self, layer_output:np.array):
        if layer_output>0:
            return 1/(1+np.exp(-layer_output)) # 1/(1+e^-z)
        else:
            return np.exp(layer_output)/(1+np.exp(layer_output)) # e^z / (1+e^z)
    

In [22]:
input_ = np.random.randn(5)

In [23]:
true_output = np.random.binomial(1, 0.5, 1)

In [24]:
true_output

array([1])

In [25]:
input_

array([-0.85246236,  0.45793525,  0.97560606, -0.29823592,  0.12522522])

In [26]:
first_layer = Dense(units = 50,activation = "relu",previous_layer = input_)

In [27]:
second_layer = Dense(5,"sigmoid", first_layer())

In [28]:
third_layer = Dense(1,"sigmoid", second_layer())

In [29]:
third_layer()

array([0.5061478], dtype=float32)

In [32]:
third_layer.previous_layer

array([0.5578409 , 0.5102446 , 0.61507595, 0.6243588 , 0.41051963],
      dtype=float32)